In [377]:
# Code to check the question, question set, model list from the replica 
# for duplicates or unfamiliar questions

In [378]:
import pandas as pd

In [379]:
df_qs = pd.read_csv('questions_package_model.csv',na_filter=False)
len(df_qs)

14985

In [380]:
df_qs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14985 entries, 0 to 14984
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   QUESTION_ID     14985 non-null  object
 1   value           14985 non-null  object
 2   QUESTIONSET_ID  14985 non-null  object
 3   MODEL_NAME      14985 non-null  object
dtypes: object(4)
memory usage: 468.4+ KB

In [381]:
# Remove questions beginning with DS and VF
df_qs = df_qs[~df_qs['QUESTION_ID'].str.startswith('DS')]
len(df_qs)

10724

In [382]:
df_qs = df_qs[~df_qs['QUESTION_ID'].str.startswith('VF')]
len(df_qs)

10456

In [383]:
df_qs = df_qs[~df_qs['QUESTION_ID'].str.startswith('CQFL')]
len(df_qs)

10128

In [384]:
df_qs = df_qs[~df_qs['QUESTION_ID'].str.startswith('CWFL')]
len(df_qs)

10073

In [385]:
df_qs = df_qs[~df_qs['QUESTION_ID'].str.startswith('KFLR')]
len(df_qs)

10066

In [386]:
df_qs = df_qs.reset_index(drop=True)
df_qs

,QUESTION_ID,value,QUESTIONSET_ID,MODEL_NAME
0,ACTIVITIES_FAMILY_LEAD_TESTED_DATE,11/7/2019,HOUSEKEEPING_PRACTICES,Childhood_Lead_Child_Model
1,HAZARD_WATER_TAP_NO,NO,LEAD_HAZARDS,Childhood_Lead_Child_Model
2,AGE_FLAG_CHILD,CHILD,ADMINISTRATIVE,Childhood_Lead_Child_Model
3,HAZARD_WATER_ASSESSMENT_YES,YES,LEAD_HAZARDS,Childhood_Lead_Child_Model
4,CHECKLIST_VACCINATIONS_NO,NO,SCHOOL_READINESS,Childhood_Lead_Child_Model
...,...,...,...,...
10061,MEDICAL_LICENSE_NUMBER,9939,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
10062,LAST_NAME,Zagorski,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
10063,CURRENT_TELEPHONE_WORK,(808) 984-3493,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
10064,SENTINEL_PROVIDER_NO,NO,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
10065,STD_SCREENING_PARTNER_NO,NO,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel

In [387]:
# Checking for duplicates 
print(df_qs[df_qs.duplicated(['QUESTION_ID','MODEL_NAME'],keep=False)].to_string())

     QUESTION_ID    value     QUESTIONSET_ID                    MODEL_NAME
7853     TOC_VIS  UNKNOWN           CLINICAL  DiseaseSurveillanceModel_STD
8851     TOC_VIS      YES  SURRG_REINTERVIEW  DiseaseSurveillanceModel_STD

In [388]:
def join_all_except_last(question,answer):

    # Check if answer matches last part of the question
    start=len(question)-len(answer)
    if(question[start:]==answer):
        return question[:start].strip('_')
    else:
        return question
    '''
    q_tokens=question.split('_')
    a_tokens = answer.split('_')
    i=0
    ignore_index=-1
    while i< len(q_tokens):
        j=0
        while j < len(a_tokens):
            if q_tokens[i]==a_tokens[j]:
                ignore_index=i
                i=len(q_tokens)
                j=len(a_tokens)
            j+=1
        i+=1
    #print(ignore_index)
    if ignore_index<0:
        return question
    else:
        out=''
        for i in range(0,ignore_index):
            out += q_tokens[i]+'_'

        return out.strip('_')
    '''

In [389]:
join_all_except_last('ACTIVITIES_FAMILY_RISK_MEMBER_EXPOSURE_TYPE_OCCUPATIONAL','TYPE_OCCUPATIONAL')

'ACTIVITIES_FAMILY_RISK_MEMBER_EXPOSURE'

In [390]:
join_all_except_last('ACTIVITIES_FAMILY_RISK_MEMBER_EXPOSURE_TYPE_OCCUPATIONAL','1.2')

'ACTIVITIES_FAMILY_RISK_MEMBER_EXPOSURE_TYPE_OCCUPATIONAL'

In [391]:
# Truncate question if answer is contained.
# If last part of question equals value then truncate the question
df_qs.loc[:,'QUESTION_ID']  = [ join_all_except_last(q,a) for q,a in zip(df_qs.loc[:,'QUESTION_ID'],df_qs.loc[:,'value'])]

In [392]:
df_duplicates = df_qs[df_qs.duplicated(['QUESTION_ID','MODEL_NAME'],keep=False)]

In [393]:
df_duplicates.to_csv('output/question_duplicates.csv',index=False)

In [394]:
len(df_duplicates)

5476

In [395]:
len(df_qs)

10066

In [396]:
df_qs=df_qs.drop_duplicates(['QUESTION_ID','MODEL_NAME'])

In [397]:
df_qs = df_qs.reset_index(drop=True)

In [398]:
df_qs

,QUESTION_ID,value,QUESTIONSET_ID,MODEL_NAME
0,ACTIVITIES_FAMILY_LEAD_TESTED_DATE,11/7/2019,HOUSEKEEPING_PRACTICES,Childhood_Lead_Child_Model
1,HAZARD_WATER_TAP,NO,LEAD_HAZARDS,Childhood_Lead_Child_Model
2,AGE_FLAG,CHILD,ADMINISTRATIVE,Childhood_Lead_Child_Model
3,HAZARD_WATER_ASSESSMENT,YES,LEAD_HAZARDS,Childhood_Lead_Child_Model
4,CHECKLIST_VACCINATIONS,NO,SCHOOL_READINESS,Childhood_Lead_Child_Model
...,...,...,...,...
6227,ACCOUNT_SUBMISSION_PREPROCESSED,YES,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
6228,CURRENT_TELEPHONE_FAX,(909) 597-2207,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
6229,MEDICAL_LICENSE_NUMBER,9939,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
6230,LAST_NAME,Zagorski,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel
6231,CURRENT_TELEPHONE_WORK,(808) 984-3493,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel

In [399]:
df_qs.value_counts(['MODEL_NAME'],dropna=False)

MODEL_NAME
DiseaseSurveillanceModel_General        3192
DiseaseSurveillanceModel_STD            1361
DiseaseSurveillanceModel_Hep             754
Childhood_Lead_Child_Model               386
ClusterModel                             205
Childhood_Lead_Investigation_Model       136
DiseaseSurveillanceModel_Coinfection     114
PortalApplicationModel                    41
EHRAndScreeningModel_STD                  22
DiseaseSurveillanceModel_AggNETSS         14
IsolationAndControlModel                   7
Name: count, dtype: int64

In [400]:
df_maven = pd.read_csv("output/maven_all_with_mmg_and_cste.csv",na_filter=False)
len(df_maven)

9501

In [401]:
df_maven.columns

Index(['Model', 'question_number', 'depth', 'Question', 'Question.Package.ID',
       'Question.Package.Name', 'Message', 'mmg_element', 'cste_element'],
      dtype='object')

In [402]:
df_maven.value_counts(['Model'],dropna=False)

Model
General                  3866
STD                      2425
Coinfection               923
Hepatitis                 901
Childhood Lead            606
Cluster                   425
Lead investigation        255
STD EHR and screening      85
Aggregate                  15
Name: count, dtype: int64

In [403]:
df_maven[df_maven.duplicated(['Question','Model'],keep=False)]

Empty DataFrame
Columns: [Model, question_number, depth, Question, Question.Package.ID, Question.Package.Name, Message, mmg_element, cste_element]
Index: []

In [404]:
# Find common elements between df_maven and df_qs
# Renaming model column to match with the second dataset
df_qs.loc[:,'Model'] = [ m.split('_')[-1].strip() if 'DiseaseSurveillanceModel_' in m else m for m in df_qs.loc[:,'MODEL_NAME']]

In [405]:
df_qs.loc[:,'Model'].value_counts(dropna=False)

Model
General                               3192
STD                                   1361
Hep                                    754
Childhood_Lead_Child_Model             386
ClusterModel                           205
Childhood_Lead_Investigation_Model     136
Coinfection                            114
PortalApplicationModel                  41
EHRAndScreeningModel_STD                22
AggNETSS                                14
IsolationAndControlModel                 7
Name: count, dtype: int64

In [406]:
df_qs.loc[:,'Model'] = ['Hepatitis' if m=='Hep' else 'Childhood Lead' if ((m=='Childhood_Lead_Child_Model') | (m=='Childhood_Lead_Investigation_Model'))
                         else 'Cluster' if m=='ClusterModel' else 'STD EHR and screening' if m=='EHRAndScreeningModel_STD' else 'Aggregate' if m=='AggNETSS' else m
                       for m in df_qs.loc[:,'Model']]

In [407]:
df_qs.loc[:,'Model'].value_counts(dropna=False)

Model
General                     3192
STD                         1361
Hepatitis                    754
Childhood Lead               522
Cluster                      205
Coinfection                  114
PortalApplicationModel        41
STD EHR and screening         22
Aggregate                     14
IsolationAndControlModel       7
Name: count, dtype: int64

In [408]:
df_qs = df_qs[['QUESTION_ID','QUESTIONSET_ID','Model']]

In [409]:
df_qs[df_qs['QUESTION_ID']=='']

     QUESTION_ID  QUESTIONSET_ID    Model
1636              ADMINISTRATIVE  General

In [410]:
df_qs=df_qs[df_qs['QUESTION_ID']!='']
df_qs = df_qs.reset_index(drop=True)
len(df_qs)

6231

In [411]:
df_qs.to_csv('output/maven_elements_database.csv',index=False)

In [412]:
df_maven = df_maven[['Model','question_number','Question','Question.Package.Name','mmg_element','cste_element','Message']]

In [413]:
def clean_up(name):
    new_name =''
    for ch in name:
        # If space, digits, uppercase letters, lowercase letters, or underscore, add it to new name otherwise ignore
        if (ord(ch)==32 or 48<=ord(ch)<=57 or 65<=ord(ch)<=90 or 97<=ord(ch)<=122 or ord(ch)==95 ):
            new_name+=ch
    return new_name.strip()

In [414]:
df_qs.loc[:,'QUESTION_ID'] = [ clean_up(q) for q in df_qs.loc[:,'QUESTION_ID']]
df_maven.loc[:,'Question'] = [clean_up(q) for q in df_maven.loc[:,'Question']]

In [415]:
df_merge = pd.merge(df_qs,df_maven,left_on=['QUESTION_ID','Model'],right_on=['Question','Model'],how='outer',indicator=True)

In [416]:
len(df_merge)

9776

In [427]:
# Question numbers are not unique but unique when combined with model
df_merge[df_merge['question_number']==211]

,QUESTION_ID,QUESTIONSET_ID,Model,question_number,Question,Question.Package.Name,mmg_element,cste_element,Message,_merge
1,NaN,NaN,Lead investigation,211.0,ABATEMENT,,,,Does this property require an abatement?,right_only
488,ATTEMPT_CONTACT_CASE_DATE_COVID19_SCREENER_FORM,ADMINISTRATIVE,General,211.0,ATTEMPT_CONTACT_CASE_DATE_COVID19_SCREENER_FORM,Administrative,,,Date of attempt to reach case for COVID19 scre...,both
4452,FR_NOTES_USER,FIELD_RECORD,Coinfection,211.0,FR_NOTES_USER,,,,User,both
4632,HAZARD_BEHAV_MOUTH,LEAD_HAZARDS,Childhood Lead,211.0,HAZARD_BEHAV_MOUTH,,,,,both
6519,NaN,NaN,Hepatitis,211.0,NOT_CRS_REASON,Hepatitis NETSS Questions,,,"> If not a case of CRS, reason",right_only
8347,NaN,NaN,STD,211.0,RSD_SECTION,,,,,right_only
8971,STATE,ADMINISTRATIVE,Cluster,211.0,STATE,,Subject Address State,,State,both

In [417]:
df_merge

,QUESTION_ID,QUESTIONSET_ID,Model,question_number,Question,Question.Package.Name,mmg_element,cste_element,Message,_merge
0,ABATEMENT,REMEDIATION_ABATEMENT,Childhood Lead,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,NaN,NaN,Lead investigation,211.0,ABATEMENT,,,,Does this property require an abatement?,right_only
2,NaN,NaN,Lead investigation,212.0,ABATEMENT_DATE,,,,Date Lead Abatement Order issued:,right_only
3,NaN,NaN,Lead investigation,213.0,ABATEMENT_DATE_RECEIVED,,,,Date Lead Abatement Plan received:,right_only
4,NaN,NaN,Lead investigation,214.0,ABATEMENT_DATE_REVIEWED_1,,,,Date Lead Abatement Plan reviewed and notifica...,right_only
...,...,...,...,...,...,...,...,...,...,...
9771,ZIP,DEMOGRAPHIC,Hepatitis,220.0,ZIP,,Subject Address ZIP Code,,,both
9772,ZIP_CODE,ADULT_LEAD,Childhood Lead,470.0,ZIP_CODE,,,,,both
9773,NaN,NaN,Coinfection,114.0,ZIP_CODE,,,,Zip code,right_only
9774,ZIP_CODE,REPORTING_MORBIDITY,STD,161.0,ZIP_CODE,,,,,both
9775,ZIP_CODE,PATIENT_INFORMATION,STD EHR and screening,14.0,ZIP_CODE,,,,Zipcode,both

In [418]:
df_merge.to_csv('output/compare_maven_excel_to_database.csv',index=False)

In [419]:
df_both = df_merge[df_merge['_merge']=='both']
df_both = df_both.drop(['_merge'],axis=1)
df_both

,QUESTION_ID,QUESTIONSET_ID,Model,question_number,Question,Question.Package.Name,mmg_element,cste_element,Message
32,ABXCHEST_YN,CLINICAL,General,1330.0,ABXCHEST_YN,Clinical,,,Did the patient have an abnormal chest X-ray?
33,ABX_EKG,CLINICAL,General,1354.0,ABX_EKG,Clinical,,,Abnormal EKG
36,ACF,CLINICAL,General,1008.0,ACF,Clinical,,,Did patient have any abnormal or significant c...
37,ACF_ABNORMAL_PUPILS,CLINICAL,General,1039.0,ACF_ABNORMAL_PUPILS,Clinical,,,> Abnormal pupils
40,ACF_ALTERED_MENTAL_STATUS_EXAM,CLINICAL,General,1050.0,ACF_ALTERED_MENTAL_STATUS_EXAM,Clinical,,,> Altered mental status by exam
...,...,...,...,...,...,...,...,...,...
9770,ZIP,DEMOGRAPHIC,General,352.0,ZIP,Demographic,Subject Address ZIP Code,,Zip
9771,ZIP,DEMOGRAPHIC,Hepatitis,220.0,ZIP,,Subject Address ZIP Code,,
9772,ZIP_CODE,ADULT_LEAD,Childhood Lead,470.0,ZIP_CODE,,,,
9774,ZIP_CODE,REPORTING_MORBIDITY,STD,161.0,ZIP_CODE,,,,
9775,ZIP_CODE,PATIENT_INFORMATION,STD EHR and screening,14.0,ZIP_CODE,,,,Zipcode

In [420]:
df_both.to_csv('output/maven_both_database_excel.csv',index=False)

In [421]:
df_db_only = df_merge[df_merge['_merge']=='left_only']
df_db_only = df_db_only.drop(['_merge'],axis=1)
df_db_only

,QUESTION_ID,QUESTIONSET_ID,Model,question_number,Question,Question.Package.Name,mmg_element,cste_element,Message
0,ABATEMENT,REMEDIATION_ABATEMENT,Childhood Lead,NaN,NaN,NaN,NaN,NaN,NaN
34,ACCOUNT_EMAIL_SENT_DATE,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel,NaN,NaN,NaN,NaN,NaN,NaN
35,ACCOUNT_SUBMISSION_PREPROCESSED,DEMOGRAPHIC_AND_PROFESSIONAL,PortalApplicationModel,NaN,NaN,NaN,NaN,NaN,NaN
113,ACTIVITY,ENV_ACTIVITY,Childhood Lead,NaN,NaN,NaN,NaN,NaN,NaN
116,ACUPUNTURE,RISK_HISTORY,Hepatitis,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9498,VACANT,REMEDIATION_ABATEMENT,Childhood Lead,NaN,NaN,NaN,NaN,NaN,NaN
9504,VACCINATED_AFTER_BIRTHDAY_VALID_DOSES_UNK,CLINICAL,General,NaN,NaN,NaN,NaN,NaN,NaN
9511,VACCINATED_BEFORE_BIRTHDAY_VALID_DOSES_UNK,CLINICAL,General,NaN,NaN,NaN,NaN,NaN,NaN
9726,WEIGHT_UNITS_KILO,CLINICAL,General,NaN,NaN,NaN,NaN,NaN,NaN
9732,WIC_MOM_PREGANCY,DEMOGRAPHICS,Childhood Lead,NaN,NaN,NaN,NaN,NaN,NaN

In [422]:
df_excel_only = df_merge[df_merge['_merge']=='right_only']
df_excel_only = df_excel_only.drop(['_merge'],axis=1)
df_excel_only

,QUESTION_ID,QUESTIONSET_ID,Model,question_number,Question,Question.Package.Name,mmg_element,cste_element,Message
1,NaN,NaN,Lead investigation,211.0,ABATEMENT,,,,Does this property require an abatement?
2,NaN,NaN,Lead investigation,212.0,ABATEMENT_DATE,,,,Date Lead Abatement Order issued:
3,NaN,NaN,Lead investigation,213.0,ABATEMENT_DATE_RECEIVED,,,,Date Lead Abatement Plan received:
4,NaN,NaN,Lead investigation,214.0,ABATEMENT_DATE_REVIEWED_1,,,,Date Lead Abatement Plan reviewed and notifica...
5,NaN,NaN,Lead investigation,216.0,ABATEMENT_DATE_REVIEWED_2,,,,Date Lead Abatement Plan reviewed and notifica...
...,...,...,...,...,...,...,...,...,...
9766,NaN,NaN,STD,395.0,ZIDO_NEONATAL_DT,,,,
9767,NaN,NaN,STD,382.0,ZIDO_PREG,,,,
9768,NaN,NaN,STD,389.0,ZIDO_PRIOR_PREG,,,,
9769,NaN,NaN,STD,383.0,ZIDO_WEEK,,,,
9773,NaN,NaN,Coinfection,114.0,ZIP_CODE,,,,Zip code

In [423]:
df_both.to_csv('output/maven_both_database_excel.csv',index=False)
df_db_only.to_csv('output/maven_database_only.csv',index=False)
df_excel_only.to_csv('output/maven_excel_only.csv',index=False)