In [45]:
# Code to get fillrate for missing elements from MVP
import pandas as pd

In [46]:
# Input file of missing elements
df_missing = pd.read_csv('output/fill_rate_missing_elements_ver2_annotated.csv',na_filter=False)
len(df_missing)

174

In [47]:
df_missing

,count_of_values,parent_question_id,question_id,model_name,case_count,fill_rate
0,571,ADD_ALTERNATE_CONTACT,ADD_ALTERNATE_CONTACT_NO,General,536547,0.106421
1,15,ADD_ALTERNATE_CONTACT,ADD_ALTERNATE_CONTACT_NO,Hepatitis,87739,0.017096
2,792,ADD_ALTERNATE_CONTACT,ADD_ALTERNATE_CONTACT_NO,STD,210577,0.376109
3,133,ADD_ALTERNATE_CONTACT,ADD_ALTERNATE_CONTACT_YES,General,536547,0.024788
4,106,ADD_ALTERNATE_CONTACT,ADD_ALTERNATE_CONTACT_YES,STD,210577,0.050338
...,...,...,...,...,...,...
169,29,UNREPORT_TO_CDC,UNREPORT_TO_CDC_YES,STD,210577,0.013772
170,1,UNREPORT_TO_CDC,UNREPORT_TO_CDC_YES,Hepatitis,87739,0.001140
171,941,WORK_WITHIN_LAST_6_MONTHS,WORK_WITHIN_LAST_6_MONTHS_NO,General,536547,0.175381
172,10,WORK_WITHIN_LAST_6_MONTHS,WORK_WITHIN_LAST_6_MONTHS_YES,General,536547,0.001864
173,14,WORKPLACE_TYPE,WORKPLACE_TYPE,General,536547,0.002609

In [48]:
# Group by parent_question_id and model_name to get the num of values reported
df_group = df_missing.groupby(by=['parent_question_id','model_name'])['count_of_values'].sum().reset_index(name='count_of_values')

In [49]:
df_group

           parent_question_id model_name  count_of_values
0       ADD_ALTERNATE_CONTACT    General              704
1       ADD_ALTERNATE_CONTACT  Hepatitis               52
2       ADD_ALTERNATE_CONTACT        STD              898
3                    AGE_DAYS    General           533666
4                    AGE_DAYS  Hepatitis            67255
..                        ...        ...              ...
95            TELEPHONE_OTHER  Hepatitis                9
96            UNREPORT_TO_CDC  Hepatitis                5
97            UNREPORT_TO_CDC        STD               30
98             WORKPLACE_TYPE    General               14
99  WORK_WITHIN_LAST_6_MONTHS    General              951

[100 rows x 3 columns]

In [50]:
df_group.loc[:,'total_cases'] =[536547 if m=='General' else 87739 if m=='Hepatitis' else 210577 if m=='STD' else 33910 if m== 'Lead' else 0 for m in df_group.loc[:,'model_name']]

In [51]:
df_group

           parent_question_id model_name  count_of_values  total_cases
0       ADD_ALTERNATE_CONTACT    General              704       536547
1       ADD_ALTERNATE_CONTACT  Hepatitis               52        87739
2       ADD_ALTERNATE_CONTACT        STD              898       210577
3                    AGE_DAYS    General           533666       536547
4                    AGE_DAYS  Hepatitis            67255        87739
..                        ...        ...              ...          ...
95            TELEPHONE_OTHER  Hepatitis                9        87739
96            UNREPORT_TO_CDC  Hepatitis                5        87739
97            UNREPORT_TO_CDC        STD               30       210577
98             WORKPLACE_TYPE    General               14       536547
99  WORK_WITHIN_LAST_6_MONTHS    General              951       536547

[100 rows x 4 columns]

In [52]:
df_group.loc[:,'fill_rate'] = [round(c*100.0/t,3) for c,t in zip(df_group.loc[:,'count_of_values'],df_group.loc[:,'total_cases'])]

In [53]:
df_group

,parent_question_id,model_name,count_of_values,total_cases,fill_rate
0,ADD_ALTERNATE_CONTACT,General,704,536547,0.131
1,ADD_ALTERNATE_CONTACT,Hepatitis,52,87739,0.059
2,ADD_ALTERNATE_CONTACT,STD,898,210577,0.426
3,AGE_DAYS,General,533666,536547,99.463
4,AGE_DAYS,Hepatitis,67255,87739,76.653
...,...,...,...,...,...
95,TELEPHONE_OTHER,Hepatitis,9,87739,0.010
96,UNREPORT_TO_CDC,Hepatitis,5,87739,0.006
97,UNREPORT_TO_CDC,STD,30,210577,0.014
98,WORKPLACE_TYPE,General,14,536547,0.003
99,WORK_WITHIN_LAST_6_MONTHS,General,951,536547,0.177

In [54]:
df_group.to_csv('output/fill_rate_missing_elements_both_parent_child.csv',index=False)