In [28]:
# Code to analyze  Lead elements from Maven

In [29]:
import pandas as pd

In [30]:
# Read data
df_maven = pd.read_csv('input/lead_elements_stats_20260810.csv',na_filter=False)
len(df_maven)

766

In [31]:
df_maven.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 766 entries, 0 to 765
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   model_name        766 non-null    object
 1   question_package  766 non-null    object
 2   UniqueID          766 non-null    object
 3   value             766 non-null    object
 4   count_of_values   766 non-null    int64
 5   case_count        766 non-null    int64
dtypes: int64(2), object(4)
memory usage: 36.0+ KB

In [32]:
df_maven

,model_name,question_package,UniqueID,value,count_of_values,case_count
0,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,ABATEMENT_NO,NO,90,74
1,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_BLL,7.8,186,188351
2,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_DATE,11/07/2019,19,188351
3,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_FIRST_NAME,unknown,92,188351
4,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_LAST_NAME,Yacapin,91,188351
...,...,...,...,...,...,...
761,Childhood_Lead_Child_Model,ADMINISTRATIVE,VENOUS_CONFIRMED_DISPLAY,True,188351,188351
762,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_NO,NO,230,188351
763,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_UNKNOWN,UNKNOWN,567,188351
764,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_YES,YES,384,188351
765,Childhood_Lead_Child_Model,ADULT_LEAD,ZIP_CODE,99999,64203,188351

In [33]:
def join_all_except_last(question,answer):

    # Check if answer matches last part of the question
    start=len(question)-len(answer)
    if(question[start:]==answer):
        return question[:start].strip('_')
    else:
        return question

In [34]:
df_maven.loc[:,'parent_question_id']  = [ join_all_except_last(q,a) for q,a in zip(df_maven.loc[:,'UniqueID'],df_maven.loc[:,'value'])]

In [35]:
df_maven

,model_name,question_package,UniqueID,value,count_of_values,case_count,parent_question_id
0,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,ABATEMENT_NO,NO,90,74,ABATEMENT
1,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_BLL,7.8,186,188351,ACTIVITIES_FAMILY_LEAD_TESTED_BLL
2,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_DATE,11/07/2019,19,188351,ACTIVITIES_FAMILY_LEAD_TESTED_DATE
3,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_FIRST_NAME,unknown,92,188351,ACTIVITIES_FAMILY_LEAD_TESTED_FIRST_NAME
4,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_LAST_NAME,Yacapin,91,188351,ACTIVITIES_FAMILY_LEAD_TESTED_LAST_NAME
...,...,...,...,...,...,...,...
761,Childhood_Lead_Child_Model,ADMINISTRATIVE,VENOUS_CONFIRMED_DISPLAY,True,188351,188351,VENOUS_CONFIRMED_DISPLAY
762,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_NO,NO,230,188351,WIC_MOM_PREGANCY
763,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_UNKNOWN,UNKNOWN,567,188351,WIC_MOM_PREGANCY
764,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_YES,YES,384,188351,WIC_MOM_PREGANCY
765,Childhood_Lead_Child_Model,ADULT_LEAD,ZIP_CODE,99999,64203,188351,ZIP_CODE

In [36]:
df_maven.loc[:,'choice_value'] = [v if u!=p else '' for v,u,p in zip(df_maven.loc[:,'value'],df_maven.loc[:,'UniqueID'],df_maven.loc[:,'parent_question_id'])]

In [37]:
df_maven

,model_name,question_package,UniqueID,value,count_of_values,case_count,parent_question_id,choice_value
0,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,ABATEMENT_NO,NO,90,74,ABATEMENT,NO
1,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_BLL,7.8,186,188351,ACTIVITIES_FAMILY_LEAD_TESTED_BLL,
2,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_DATE,11/07/2019,19,188351,ACTIVITIES_FAMILY_LEAD_TESTED_DATE,
3,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_FIRST_NAME,unknown,92,188351,ACTIVITIES_FAMILY_LEAD_TESTED_FIRST_NAME,
4,Childhood_Lead_Child_Model,HOUSEKEEPING_PRACTICES,ACTIVITIES_FAMILY_LEAD_TESTED_LAST_NAME,Yacapin,91,188351,ACTIVITIES_FAMILY_LEAD_TESTED_LAST_NAME,
...,...,...,...,...,...,...,...,...
761,Childhood_Lead_Child_Model,ADMINISTRATIVE,VENOUS_CONFIRMED_DISPLAY,True,188351,188351,VENOUS_CONFIRMED_DISPLAY,
762,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_NO,NO,230,188351,WIC_MOM_PREGANCY,NO
763,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_UNKNOWN,UNKNOWN,567,188351,WIC_MOM_PREGANCY,UNKNOWN
764,Childhood_Lead_Child_Model,DEMOGRAPHICS,WIC_MOM_PREGANCY_YES,YES,384,188351,WIC_MOM_PREGANCY,YES
765,Childhood_Lead_Child_Model,ADULT_LEAD,ZIP_CODE,99999,64203,188351,ZIP_CODE,

In [38]:
# Group by parent question to get completion rates
df_group = df_maven.groupby(by= ['model_name','question_package','parent_question_id','case_count'])['count_of_values'].sum().reset_index(name= 'count_of_values')

In [39]:
df_group

,model_name,question_package,parent_question_id,case_count,count_of_values
0,Childhood_Lead_Child_Model,ADMINISTRATIVE,AGE_FLAG,188351,130995
1,Childhood_Lead_Child_Model,ADMINISTRATIVE,ANY_OVER_5_OUTPUT,188351,188351
2,Childhood_Lead_Child_Model,ADMINISTRATIVE,BLL_DECLINE_OUTPUT,188351,188351
3,Childhood_Lead_Child_Model,ADMINISTRATIVE,BLL_TOTAL_DECLINING_OUTPUT,188351,801236
4,Childhood_Lead_Child_Model,ADMINISTRATIVE,CASE_CLOSURE_DATE,188351,5
...,...,...,...,...,...
517,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,REMEDIATION_POST_REPORT_DATE,74,1
518,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,REMEDIATION_REINSPECTION_DATE,74,1
519,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,REMEDIATION_REOCCUPANCY_INSPECTION_DATE_1,74,1
520,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,SIGNED_AGREEMENT,74,60
521,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,VACANT,74,110

In [40]:
df_group.loc[:,'fill_rate'] = [round(n*100.0/d,3) for n,d in zip(df_group.loc[:,'count_of_values'],df_group.loc[:,'case_count'])]

In [41]:
df_group

,model_name,question_package,parent_question_id,case_count,count_of_values,fill_rate
0,Childhood_Lead_Child_Model,ADMINISTRATIVE,AGE_FLAG,188351,130995,69.548
1,Childhood_Lead_Child_Model,ADMINISTRATIVE,ANY_OVER_5_OUTPUT,188351,188351,100.000
2,Childhood_Lead_Child_Model,ADMINISTRATIVE,BLL_DECLINE_OUTPUT,188351,188351,100.000
3,Childhood_Lead_Child_Model,ADMINISTRATIVE,BLL_TOTAL_DECLINING_OUTPUT,188351,801236,425.395
4,Childhood_Lead_Child_Model,ADMINISTRATIVE,CASE_CLOSURE_DATE,188351,5,0.003
...,...,...,...,...,...,...
517,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,REMEDIATION_POST_REPORT_DATE,74,1,1.351
518,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,REMEDIATION_REINSPECTION_DATE,74,1,1.351
519,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,REMEDIATION_REOCCUPANCY_INSPECTION_DATE_1,74,1,1.351
520,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,SIGNED_AGREEMENT,74,60,81.081
521,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,VACANT,74,110,148.649

In [42]:
#df_group = df_group[['model_name','question_package','parent_question_id','fill_rate']]

In [43]:
df_group.to_csv('output/lead_elements_analysis_output.csv',index=False)

In [44]:
#STOP

In [45]:
# Merge with file from Jennifer to get the display text column

In [46]:
df_other = pd.read_csv('input/LEAD_Migrated_fields_Maven_DB_JL.csv',na_filter=False)
len(df_other)

1473

In [47]:
df_other

,Model,PackageID,UniqueID,ParentQuestionID,ChoiceValue,DisplayText,Fill Rate,ELR Fields
0,Childhood_Lead_Child_Model,ADMINISTRATIVE,AGE_FLAG_ADULT,AGE_FLAG,ADULT,Adult Labs,,
1,Childhood_Lead_Child_Model,ADMINISTRATIVE,AGE_FLAG_CHILD,AGE_FLAG,CHILD,Child Labs,,
2,Childhood_Lead_Child_Model,ADMINISTRATIVE,AGE_FLAG_MIXED,AGE_FLAG,MIXED,Child and Adult Mixed Labs,,
3,Childhood_Lead_Child_Model,ADMINISTRATIVE,AGE_FLAG_UNKNOWN,AGE_FLAG,UNKNOWN,Missing Information,,
4,Childhood_Lead_Child_Model,ADMINISTRATIVE,ANY_OVER_5_OUTPUT,,,This Is a Case (>=5 Capillary or Venous):,,
...,...,...,...,...,...,...,...,...
1468,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,REMEDIATION_YES,REMEDIATION,YES,Yes,,
1469,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,SIGNED_AGREEMENT_NO,SIGNED_AGREEMENT,NO,No,,
1470,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,SIGNED_AGREEMENT_YES,SIGNED_AGREEMENT,YES,Yes,,
1471,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,VACANT_NO,VACANT,NO,No,,
1472,Childhood_Lead_Investigation_Model,REMEDIATION_ABATEMENT,VACANT_YES,VACANT,YES,Yes,,

In [48]:
# Merger df_group with df_other on parent_question_id
df_merge = pd.merge(df_group,df_other,)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False